package dibujargrafo;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.GroupLayout.Alignment.CENTER;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesús Lozano
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    ArrayList<Nodo> lista = new ArrayList();
    Nodo seleccionado = null;
    BufferedImage icono = Metodos.cargarImagen("icon");
    BufferedImage iconoSeleccionado = Metodos.cargarImagen("icon-selected");
    BufferedImage icono2 = Metodos.cargarImagen("icon2");
    BufferedImage iconoSeleccionado2 = Metodos.cargarImagen("icon2-selected");
    int xtemp, ytemp, cont = 0;
    boolean with_name = false, first_init = true, green_light = false;

    public Principal() throws IOException {
        initComponents();
        setEnableRec(info, false); //Se inician los componentes del formulario inhabilitados
        rela.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        info = new javax.swing.JPanel();
        name_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gender_box = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        agregar = new javax.swing.JButton();
        espanol = new javax.swing.JCheckBox();
        ingles = new javax.swing.JCheckBox();
        frances = new javax.swing.JCheckBox();
        aleman = new javax.swing.JCheckBox();
        mandarin = new javax.swing.JCheckBox();
        todos = new javax.swing.JCheckBox();
        portugues = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rela = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        familiar = new javax.swing.JButton();
        amigos = new javax.swing.JButton();
        feme = new javax.swing.JButton();
        mascu = new javax.swing.JButton();
        idi = new javax.swing.JComboBox<>();
        busc = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1024, 768));
        setLocationByPlatform(true);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setPreferredSize(new java.awt.Dimension(800, 580));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMouseReleased(evt);
            }
        });
        panel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelComponentShown(evt);
            }
        });
        panel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                panelPropertyChange(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mapa1.png"))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(191, 54, 12));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Social Network");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(514, 514, 514))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        info.setBackground(new java.awt.Color(224, 224, 224));

        name_field.setToolTipText("Nombre");
        name_field.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");

        gender_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setText("Sexo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setText("Idiomas:");

        jPanel2.setBackground(new java.awt.Color(191, 54, 12));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        espanol.setText("Español");
        espanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espanolActionPerformed(evt);
            }
        });

        ingles.setText("Inglés");

        frances.setText("Francés");

        aleman.setText("Alemán");

        mandarin.setText("Mandarín");

        todos.setText("Todos");
        todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosActionPerformed(evt);
            }
        });

        portugues.setText("Portugués");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender_box, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espanol)
                            .addComponent(aleman))
                        .addGap(10, 10, 10)
                        .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(infoLayout.createSequentialGroup()
                                .addComponent(ingles)
                                .addGap(10, 10, 10)
                                .addComponent(frances))
                            .addGroup(infoLayout.createSequentialGroup()
                                .addComponent(mandarin)
                                .addGap(10, 10, 10)
                                .addComponent(portugues))))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(todos)
                        .addGap(92, 92, 92)
                        .addComponent(agregar)))
                .addGap(14, 14, 14))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gender_box, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espanol)
                    .addComponent(ingles)
                    .addComponent(frances))
                .addGap(15, 15, 15)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aleman)
                    .addComponent(mandarin)
                    .addComponent(portugues))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregar)
                    .addComponent(todos))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(224, 224, 224));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setText("Relación:");

        rela.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "amigo", "padre", "madre", "hermano(a)", "primo(a)", "sobrino(a)", "abuel(a)", "tío(a)" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(rela, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rela, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(224, 224, 224));

        familiar.setText("Familiares");
        familiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familiarActionPerformed(evt);
            }
        });

        amigos.setText("Amigos");
        amigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amigosActionPerformed(evt);
            }
        });

        feme.setText("Femeninos");
        feme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femeActionPerformed(evt);
            }
        });

        mascu.setText("masculino");
        mascu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mascuActionPerformed(evt);
            }
        });

        idi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés", "Francés", "Alemán", "Mandarín", "Portugués" }));

        busc.setText("buscar");
        busc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Idioma");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(feme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mascu))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(familiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amigos))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(idi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(busc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(familiar)
                    .addComponent(amigos))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feme)
                    .addComponent(mascu))
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busc))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(191, 54, 12));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        result.setColumns(20);
        result.setRows(5);
        jScrollPane1.setViewportView(result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setEnableRec(Component container, boolean enable) {     //Inhabilita y habilita todos los componentes del formulario
        container.setEnabled(enable);
        try {
            Component[] components = ((Container) container).getComponents();
            for (int i = 0; i < components.length; i++) {
                setEnableRec(components[i], enable);
            }
        } catch (ClassCastException e) {

        }
    }

    private void clear() {
        name_field.setText("");

    }

    private void panelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseReleased
        xtemp = evt.getX();  //Se obtiene las coordenadas
        ytemp = evt.getY();  //donde se pondra el nodo
        if (Metodos.colisiona(xtemp, ytemp, 50, lista) && cont >= 2) {
            green_light = true;
            setNodeMain(icono, iconoSeleccionado, "noName", 'm', null);
        } else if (Metodos.colisiona(xtemp, ytemp, 50, lista) == false) {
            setEnableRec(info, true);
            rela.setEnabled(true);
            with_name = false;
            first_init = false;
        }
    }//GEN-LAST:event_panelMouseReleased

    private void setNodeMain(BufferedImage ico, BufferedImage s_ico, String nam, Character gen, ArrayList<String> idi) {

        int d = 50, r = d / 2;
        int x = xtemp;
        int y = ytemp;

        int ancho = panel.getWidth(), alto = panel.getHeight();
        if (seleccionado == null) {
            seleccionado = Metodos.seleccionar(x, y, d, lista);

            if (seleccionado != null) {

                /*System.out.println("Nombre: " + seleccionado.getName());
                System.out.println("Genero: " + seleccionado.getGen());
                System.out.print("Idiomas: ");
                for (String ite : seleccionado.getLeng()) {
                    System.out.print(ite + ", ");
                }
                System.out.println("");
                System.out.println("");
                System.out.println("Relacionados");
                for (Nodo ite : seleccionado.getRelated()) {
                    System.out.print(ite.getName() + ", ");
                }
                System.out.println("");
                System.out.println("--------------------------------------");*/
                if (seleccionado.getGen() == 'f') {
                    Metodos.dibujarIcono(iconoSeleccionado2, seleccionado.getX(), seleccionado.getY(), panel);
                } else {
                    Metodos.dibujarIcono(iconoSeleccionado, seleccionado.getX(), seleccionado.getY(), panel);
                }
                for (int i = 0; i < seleccionado.getRelated().size(); i++) {
                    if (seleccionado.getRelated().contains(seleccionado)) {
                        seleccionado.getRelated().remove(seleccionado);
                    }
                }
            } else {
                if (Metodos.sePuedeDibujar(x, y, r, ancho, alto)) {
                    if (!Metodos.colisiona(x, y, d, lista)) {
                        int red = (int) (Math.random() * 255);
                        int green = (int) (Math.random() * 255);
                        int blue = (int) (Math.random() * 255);
                        Color c = new Color(red, green, blue);
                        Metodos.dibujarIcono(ico, x, y, panel);
                        lista.add(new Nodo(x, y, d, c, nam, gen, idi));
                    }
                }
                seleccionado = null;
            }
        } else {
            Nodo destino = Metodos.seleccionar(x, y, d, lista);

            if (destino != null) {
                Character g = destino.getGen();
                Metodos.dibujarLinea(seleccionado.getX(), seleccionado.getY(), destino.getX(), destino.getY(), panel);

                if (g == 'f') {
                    Metodos.dibujarIcono(icono2, destino.getX(), destino.getY(), panel);
                } else {
                    Metodos.dibujarIcono(icono, destino.getX(), destino.getY(), panel);
                }

                for (int i = 0; i < seleccionado.getRelated().size(); i++) {
                    if (seleccionado.getRelated().contains(seleccionado)) {
                        seleccionado.getRelated().remove(seleccionado);
                    }
                    if (seleccionado.getRelated().contains(destino)) {
                        seleccionado.getRelated().contains(destino);
                    }
                    if (destino.getRelated().contains(destino)) {
                        destino.getRelated().remove(destino);
                    }
                    if (destino.getRelated().contains(seleccionado)) {
                        destino.getRelated().remove(seleccionado);
                    }
                }
                for (int i = 0; i < seleccionado.getRelated().size(); i++) {
                    if (destino.getRelated().contains(destino)) {
                        destino.getRelated().remove(destino);
                    }
                    if (destino.getRelated().contains(seleccionado)) {
                        destino.getRelated().remove(seleccionado);
                    }
                }
                /*seleccionado.setRelacion(rela.getSelectedItem().toString());
                destino.setRelacion(rela.getSelectedItem().toString());
                seleccionado.getRelated().add(destino);
                destino.getRelated().add(seleccionado);*/
                setRelation(seleccionado, destino);
                destino = null;

            } //end if

            if (seleccionado.getGen() == 'f') {
                Metodos.dibujarIcono(icono2, seleccionado.getX(), seleccionado.getY(), panel);
                seleccionado = null;
            } else {
                Metodos.dibujarIcono(icono, seleccionado.getX(), seleccionado.getY(), panel);
                seleccionado = null;
            }
            seleccionado = null;
        }
    }

    private void setRelation(Nodo seleccionado, Nodo destino) {
        if (rela.getSelectedItem().toString().equals("padre") || rela.getSelectedItem().toString().equals("madre")) {
            seleccionado.setRelacion(rela.getSelectedItem().toString());
            destino.setRelacion("Hijo(a)");
            destino.getRelated().add(seleccionado);
            seleccionado.getRelated().add(destino);
        } else if (rela.getSelectedItem().toString().equals("sobrino(a)")) {
            seleccionado.setRelacion(rela.getSelectedItem().toString());
            destino.setRelacion("tío(a)");
            destino.getRelated().add(seleccionado);
            seleccionado.getRelated().add(destino);
        } else if (rela.getSelectedItem().toString().equals("tío(a)")) {
            seleccionado.setRelacion(rela.getSelectedItem().toString());
            destino.setRelacion("sobrino(a)");
            destino.getRelated().add(seleccionado);
            seleccionado.getRelated().add(destino);
        } else if (rela.getSelectedItem().toString().equals("primo(a)") || rela.getSelectedItem().toString().equals("amigo") || rela.getSelectedItem().toString().equals(" hermano(a)")) {
            seleccionado.setRelacion(rela.getSelectedItem().toString());
            destino.setRelacion(rela.getSelectedItem().toString());
            seleccionado.getRelated().add(destino);
            destino.getRelated().add(seleccionado);
        }
    }

    private void panelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelComponentShown

    }//GEN-LAST:event_panelComponentShown

    private void panelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_panelPropertyChange

    }//GEN-LAST:event_panelPropertyChange
    private boolean check() {
        if (!espanol.isSelected() && !ingles.isSelected() && !aleman.isSelected() && !mandarin.isSelected() && !frances.isSelected() && !portugues.isSelected() && !todos.isSelected()) {
            return true;
        }
        return false;
    }
    private void familiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familiarActionPerformed
        String cad = "";
        if (seleccionado != null) {
            System.out.println("Relacionados");
            for (Nodo ite : seleccionado.getRelated()) {

                if (ite.getRelacion().equalsIgnoreCase("amigo") == false) {
                    cad = cad + result.getText() + ite.getName();
                    System.out.print(ite.getName() + "(" + (ite.getRelacion()) + ")" + ", ");
                }
            }
            System.out.println("");
            System.out.println("--------------------------------------");
            result.setText(cad);
        }
    }//GEN-LAST:event_familiarActionPerformed

    private void todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosActionPerformed
        espanol.setEnabled(false);
        ingles.setEnabled(false);
        mandarin.setEnabled(false);
        portugues.setEnabled(false);
        frances.setEnabled(false);
        aleman.setEnabled(false);
    }//GEN-LAST:event_todosActionPerformed

    private void espanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espanolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espanolActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if (name_field.getText().equalsIgnoreCase("") || check()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos antes de continuar");
        } else {
            if (gender_box.getSelectedItem().toString().equalsIgnoreCase("Masculino")) {
                putName();
                setNodeMain(icono, iconoSeleccionado, name_field.getText(), 'm', addLang());
                cont++;
            } else {
                putName();
                setNodeMain(icono2, iconoSeleccionado2, name_field.getText(), 'f', addLang());
                cont++;
            }

            with_name = true;
            setEnableRec(info, false);
            clear();
        }

    }//GEN-LAST:event_agregarActionPerformed

    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fieldActionPerformed

    private void amigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amigosActionPerformed
        String cad = "";
        if (seleccionado != null) {
            for (Nodo ite : seleccionado.getRelated()) {

                if (ite.getRelacion().equalsIgnoreCase("amigo")) {
                    cad = cad + result.getText() + ite.getName();
                    System.out.print(ite.getName() + "(" + (ite.getRelacion()) + ")" + ", ");
                }
            }
            System.out.println("");
            System.out.println("--------------------------------------");
            result.setText(cad);
        }
    }//GEN-LAST:event_amigosActionPerformed

    private void femeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femeActionPerformed
       result.setText("");
        String cad = "";
        for (Nodo ite : lista) {

            if (ite.getGen() == 'f') {
                cad = cad + result.getText() + ite.getName();
                System.out.print(ite.getName() + "(" + (ite.getRelacion()) + ")" + ", ");
            }
        }
        result.setText(cad);
    }//GEN-LAST:event_femeActionPerformed

    private void mascuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mascuActionPerformed
        result.setText("");
        String cad = "";
        for (Nodo ite : lista) {

            if (ite.getGen() == 'm') {
                cad = cad + result.getText() + ite.getName();
                System.out.print(ite.getName() + "(" + (ite.getRelacion()) + ")" + ", ");
            }
        }
        result.setText(cad);
    }//GEN-LAST:event_mascuActionPerformed

    private void buscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscActionPerformed
        result.setText("");     
        String cad = "";
        for (Nodo ite : lista) {
            for (String ite2 : ite.getLeng()) {
                if (ite2.equalsIgnoreCase(idi.getSelectedItem().toString())) {
                    cad = cad + result.getText() + ite.getName();
                    System.out.print(ite.getName() + "(" + (ite.getRelacion()) + ")" + ", ");
                }
            }

        }
        result.setText(cad);
    }//GEN-LAST:event_buscActionPerformed

    private void putName() {
        JLabel namelbl = new JLabel(name_field.getText());  //Se crea un nuevo label para mostrar el nombre
        jLabel1.add(namelbl);
        namelbl.setLocation(xtemp - 40, ytemp + 15);
        namelbl.setSize(80, 13);
        namelbl.setHorizontalAlignment(0);
        namelbl.setHorizontalTextPosition(0);
        namelbl.setFont(new Font("Dialog", Font.BOLD, 12));
        namelbl.setBackground(new Color(0, 0, 0, 0));
    }

    private ArrayList<String> addLang() {  //Agrega los idiomas a las persona
        ArrayList<String> idiomas = new ArrayList<String>();
        if (todos.isSelected()) {
            idiomas.add("Español");
            idiomas.add("Inglés");
            idiomas.add("Francés");
            idiomas.add("Alemán");
            idiomas.add("Mandarín");
            idiomas.add("Portugués");
            return (idiomas);
        } else {
            if (espanol.isSelected()) {
                idiomas.add("Español");
            }
            if (ingles.isSelected()) {
                idiomas.add("Inglés");
            }
            if (frances.isSelected()) {
                idiomas.add("Francés");
            }
            if (aleman.isSelected()) {
                idiomas.add("Alemán");
            }
            if (mandarin.isSelected()) {
                idiomas.add("Mandarín");
            }
            if (portugues.isSelected()) {
                idiomas.add("Portugués");
            }
        }
        return (idiomas);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);

                } catch (IOException ex) {
                    Logger.getLogger(Principal.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JCheckBox aleman;
    private javax.swing.JButton amigos;
    private javax.swing.JButton busc;
    private javax.swing.JCheckBox espanol;
    private javax.swing.JButton familiar;
    private javax.swing.JButton feme;
    private javax.swing.JCheckBox frances;
    private javax.swing.JComboBox<String> gender_box;
    private javax.swing.JComboBox<String> idi;
    private javax.swing.JPanel info;
    private javax.swing.JCheckBox ingles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mandarin;
    private javax.swing.JButton mascu;
    private javax.swing.JTextField name_field;
    private javax.swing.JPanel panel;
    private javax.swing.JCheckBox portugues;
    private javax.swing.JComboBox<String> rela;
    private javax.swing.JTextArea result;
    private javax.swing.JCheckBox todos;
    // End of variables declaration//GEN-END:variables
}
